<?php
/**
 * Site-wide block and pattern inventory.
 *
 * Scans all published posts/pages to gather block usage counts, namespace
 * totals, pattern references, and non-preferred pattern detection. Future
 * home for storage-mode auto-discovery and other "what blocks live on this
 * site, and what do we know about them" intelligence.
 *
 * Renamed from Usage_Stats — the original name implied dashboard-style
 * numeric rollups, but this class actually owns broader inventory data.
 *
 * @package GravityKit\BlockAPI
 */

namespace GravityKit\BlockAPI;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Block_Inventory
 *
 * Cached site-wide block + pattern inventory.
 */
class Block_Inventory {

	/**
	 * Transient key for the cached inventory.
	 *
	 * @var string
	 */
	const CACHE_KEY = 'gk_block_inventory';

	/**
	 * Cache TTL in seconds (1 hour).
	 *
	 * @var int
	 */
	const CACHE_TTL = HOUR_IN_SECONDS;

	/**
	 * Storage-mode constants. Use these instead of the bare strings so
	 * a typo doesn't silently mis-classify a block. Surface in API
	 * responses as the underlying string value.
	 */
	const STORAGE_MODE_STATIC  = 'static';
	const STORAGE_MODE_DYNAMIC = 'dynamic';
	const STORAGE_MODE_DUAL    = 'dual';

	// ──────────────────────────────────────────────────────────────────
	// Storage-mode classification.
	//
	// "What kind of block is this?" — static / dynamic / dual. Lives here
	// (not in Block_CRUD) because it's inventory metadata about block
	// types, not a write-time concern. Block_CRUD consults this layer
	// when annotating get_page_blocks responses and when enforcing the
	// "dual blocks need both fields" rule (BLOCK-14).
	//
	// BLOCK-13 will extend this with site-scan auto-discovery that
	// persists findings to `wp_options.gk_block_api_storage_modes`.
	// ──────────────────────────────────────────────────────────────────

	/**
	 * Resolve the storage mode for a block: "static" | "dynamic" | "dual".
	 *
	 * - "static": innerHTML is the source of truth (most core/* blocks).
	 * - "dynamic": attributes is the source of truth; innerHTML is
	 *   regenerated on render (e.g., core/post-title, query loops).
	 * - "dual": BOTH attributes and innerHTML carry the same data and
	 *   must be kept in sync (e.g., yoast/faq-block.questions[]).
	 *
	 * Site admins can extend the dual-storage list via the
	 * `gk_block_api_dual_storage_blocks` filter.
	 *
	 * @param string $block_name Fully-qualified block name.
	 * @param bool   $is_dynamic Whether the registered block is server-rendered.
	 * @return string
	 */
	public function resolve_storage_mode( $block_name, $is_dynamic ) {
		if ( $this->is_dual_storage_block( $block_name ) ) {
			return self::STORAGE_MODE_DUAL;
		}
		return $is_dynamic ? self::STORAGE_MODE_DYNAMIC : self::STORAGE_MODE_STATIC;
	}

	/**
	 * Whether a block name is configured (or auto-discovered) as dual-storage.
	 *
	 * @param string $block_name Fully-qualified block name.
	 * @return bool
	 */
	public function is_dual_storage_block( $block_name ) {
		static $cache = null;
		if ( null === $cache ) {
			/**
			 * Filter the list of block names treated as dual-storage.
			 *
			 * Dual-storage blocks store the same content in both
			 * `attributes` and `innerHTML` and require both to be kept
			 * in sync.
			 *
			 * @param string[] $dual_blocks Block names considered dual-storage.
			 */
			$dual_blocks = (array) apply_filters(
				'gk_block_api_dual_storage_blocks',
				array(
					'yoast/faq-block',
					'yoast/how-to-block',
				)
			);
			$cache = array_flip( $dual_blocks );
		}
		return isset( $cache[ $block_name ] );
	}

	/**
	 * Whether a registered block type is server-rendered.
	 *
	 * Cached per block name. Wraps WP_Block_Type_Registry to give
	 * Block_CRUD a single discovery point that can be replaced by the
	 * scan-cached map once BLOCK-13 lands.
	 *
	 * @param string $block_name Fully-qualified block name.
	 * @return bool
	 */
	public function is_dynamic_block( $block_name ) {
		static $cache = array();
		if ( ! isset( $cache[ $block_name ] ) ) {
			$registry        = \WP_Block_Type_Registry::get_instance();
			$type            = $registry ? $registry->get_registered( $block_name ) : null;
			$cache[ $block_name ] = $type ? $type->is_dynamic() : false;
		}
		return $cache[ $block_name ];
	}

	/**
	 * Get block and pattern usage statistics.
	 *
	 * Returns cached data unless $refresh is true, in which case the cache
	 * is regenerated by scanning all published content.
	 *
	 * @param bool $refresh Force cache regeneration.
	 *
	 * @return array {
	 *     @type array $block_usage       Block name => { count, post_count }.
	 *     @type array $namespace_totals  Namespace => total block count.
	 *     @type array $pattern_references Pattern ID => { name, refs }.
	 *     @type array $legacy_patterns   List of patterns containing legacy blocks.
	 * }
	 */
	public function get_stats( $refresh = false ) {
		if ( ! $refresh ) {
			$cached = get_transient( self::CACHE_KEY );

			if ( false !== $cached ) {
				return $cached;
			}
		}

		try {
			$stats = $this->build_stats();
		} catch ( \Throwable $e ) {
			if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
				error_log( 'GK Block API stats build error: ' . $e->getMessage() );
			}
			$stats = array(
				'block_usage'        => array(),
				'namespace_totals'   => array(),
				'pattern_references' => array(),
				'legacy_patterns'    => array(),
			);
		}

		set_transient( self::CACHE_KEY, $stats, self::CACHE_TTL );

		return $stats;
	}

	/**
	 * Get usage data for a specific block type.
	 *
	 * @param string $block_name Full block name (e.g., "core/paragraph").
	 *
	 * @return array { count, post_count } or empty defaults.
	 */
	public function get_block_usage( $block_name ) {
		$stats = $this->get_stats();

		if ( isset( $stats['block_usage'][ $block_name ] ) ) {
			return $stats['block_usage'][ $block_name ];
		}

		return array(
			'count'      => 0,
			'post_count' => 0,
		);
	}

	/**
	 * Scan all published content and build usage statistics.
	 *
	 * @return array Structured usage stats.
	 */
	private function build_stats() {
		$block_usage        = array();
		$namespace_totals   = array();
		$pattern_refs       = array();
		$posts_per_block    = array();

		// Query all published posts and pages with block content.
		$post_types = get_post_types( array( 'public' => true ), 'names' );

		$query_args = array(
			'post_type'      => array_values( $post_types ),
			'post_status'    => 'publish',
			'posts_per_page' => -1,
			'no_found_rows'  => true,
			'fields'         => 'ids',
		);

		$post_ids = get_posts( $query_args );

		foreach ( $post_ids as $post_id ) {
			$content = get_post_field( 'post_content', $post_id );

			if ( empty( $content ) || ! has_blocks( $content ) ) {
				continue;
			}

			$blocks = parse_blocks( $content );
			if ( ! is_array( $blocks ) ) {
				continue;
			}
			$this->count_blocks( $blocks, $post_id, $block_usage, $posts_per_block, $namespace_totals, $pattern_refs );
		}

		// Merge post_count into block_usage.
		foreach ( $block_usage as $name => &$data ) {
			$data['post_count'] = isset( $posts_per_block[ $name ] )
				? count( $posts_per_block[ $name ] )
				: 0;
		}
		unset( $data );

		// Sort block_usage by count descending.
		uasort( $block_usage, function ( $a, $b ) {
			return $b['count'] - $a['count'];
		} );

		// Sort namespace totals descending.
		arsort( $namespace_totals );

		// Resolve pattern names and detect legacy patterns.
		$pattern_references = $this->resolve_pattern_references( $pattern_refs );
		$legacy_patterns    = $this->detect_legacy_patterns( $pattern_references );

		return array(
			'block_usage'        => $block_usage,
			'namespace_totals'   => $namespace_totals,
			'pattern_references' => $pattern_references,
			'legacy_patterns'    => $legacy_patterns,
		);
	}

	/**
	 * Recursively count blocks within a block array.
	 *
	 * @param array $blocks          Parsed blocks array.
	 * @param int   $post_id         Current post ID.
	 * @param array &$block_usage    Running count per block name.
	 * @param array &$posts_per_block Post IDs per block name (for post_count).
	 * @param array &$namespace_totals Running count per namespace.
	 * @param array &$pattern_refs   Running count of core/block refs.
	 */
	private function count_blocks( $blocks, $post_id, &$block_usage, &$posts_per_block, &$namespace_totals, &$pattern_refs ) {
		foreach ( $blocks as $block ) {
			$name = $block['blockName'];

			// Skip null/empty block names (freeform HTML, whitespace).
			if ( empty( $name ) ) {
				continue;
			}

			// Count the block.
			if ( ! isset( $block_usage[ $name ] ) ) {
				$block_usage[ $name ] = array( 'count' => 0 );
			}
			$block_usage[ $name ]['count']++;

			// Track which posts use this block.
			if ( ! isset( $posts_per_block[ $name ] ) ) {
				$posts_per_block[ $name ] = array();
			}
			$posts_per_block[ $name ][ $post_id ] = true;

			// Namespace total.
			$namespace = explode( '/', $name, 2 );
			$ns        = $namespace[0];
			if ( ! isset( $namespace_totals[ $ns ] ) ) {
				$namespace_totals[ $ns ] = 0;
			}
			$namespace_totals[ $ns ]++;

			// Track synced pattern references (core/block with ref attribute).
			if ( 'core/block' === $name && ! empty( $block['attrs']['ref'] ) ) {
				$ref_id = (int) $block['attrs']['ref'];
				if ( ! isset( $pattern_refs[ $ref_id ] ) ) {
					$pattern_refs[ $ref_id ] = 0;
				}
				$pattern_refs[ $ref_id ]++;
			}

			// Recurse into inner blocks.
			if ( ! empty( $block['innerBlocks'] ) ) {
				$this->count_blocks( $block['innerBlocks'], $post_id, $block_usage, $posts_per_block, $namespace_totals, $pattern_refs );
			}
		}
	}

	/**
	 * Resolve pattern reference IDs to names and ref counts.
	 *
	 * @param array $pattern_refs Pattern ID => count.
	 *
	 * @return array Pattern ID => { name, refs }.
	 */
	private function resolve_pattern_references( $pattern_refs ) {
		$resolved = array();

		foreach ( $pattern_refs as $pattern_id => $count ) {
			$pattern = get_post( $pattern_id );

			if ( $pattern && 'wp_block' === $pattern->post_type ) {
				$resolved[ $pattern_id ] = array(
					'name' => $pattern->post_title,
					'refs' => $count,
				);
			} else {
				$resolved[ $pattern_id ] = array(
					'name' => __( '(deleted pattern)', 'gk-block-api' ),
					'refs' => $count,
				);
			}
		}

		// Sort by refs descending.
		uasort( $resolved, function ( $a, $b ) {
			return $b['refs'] - $a['refs'];
		} );

		return $resolved;
	}

	/**
	 * Detect synced patterns (wp_block posts) that contain legacy blocks.
	 *
	 * @param array $pattern_references Already-computed pattern references from build_stats().
	 *
	 * @return array List of legacy pattern data.
	 */
	private function detect_legacy_patterns( $pattern_references ) {
		$preferences = new Preferences();
		$legacy      = array();

		$patterns = get_posts( array(
			'post_type'      => 'wp_block',
			'post_status'    => 'publish',
			'posts_per_page' => -1,
			'no_found_rows'  => true,
		) );

		foreach ( $patterns as $pattern ) {
			if ( empty( $pattern->post_content ) || ! has_blocks( $pattern->post_content ) ) {
				continue;
			}

			$blocks = parse_blocks( $pattern->post_content );
			if ( ! is_array( $blocks ) ) {
				continue;
			}
			$legacy_blocks = $this->find_legacy_blocks( $blocks, $preferences );

			if ( ! empty( $legacy_blocks ) ) {
				// Count references to this pattern using the already-computed data.
				$refs = isset( $pattern_references[ $pattern->ID ] )
					? $pattern_references[ $pattern->ID ]['refs']
					: 0;

				$legacy[] = array(
					'id'            => $pattern->ID,
					'name'          => $pattern->post_title,
					'refs'          => $refs,
					'legacy_blocks' => array_unique( $legacy_blocks ),
				);
			}
		}

		return $legacy;
	}

	/**
	 * Recursively find legacy block names in a block array.
	 *
	 * @param array       $blocks      Parsed blocks.
	 * @param Preferences $preferences Preferences instance.
	 *
	 * @return string[] Legacy block names found.
	 */
	private function find_legacy_blocks( $blocks, $preferences ) {
		$legacy = array();

		foreach ( $blocks as $block ) {
			if ( empty( $block['blockName'] ) ) {
				continue;
			}

			if ( $preferences->is_legacy_block( $block['blockName'] ) ) {
				$legacy[] = $block['blockName'];
			}

			if ( ! empty( $block['innerBlocks'] ) ) {
				$legacy = array_merge( $legacy, $this->find_legacy_blocks( $block['innerBlocks'], $preferences ) );
			}
		}

		return $legacy;
	}
}
