<?php
/**
 * Abilities API registration and tool execution tests.
 *
 * @package GravityKit\BlockMCP\Tests
 */

declare( strict_types=1 );

use GravityKit\BlockMCP\Abilities_Registry;
use GravityKit\BlockMCP\Block_Abilities;
use GravityKit\BlockMCP\Tool_Executor;
use GravityKit\BlockMCP\Yoast_Bridge;
use function GravityKit\BlockMCP\get_abilities_registry;

/**
 * Covers the exported tool manifest and in-process tool execution.
 */
class AbilitiesRegistryTest extends RestControllerTestCase {

	/**
	 * Registration defaults to opt-in (off); enable it so the WordPress
	 * Abilities API registry — a lazily-initialized singleton that fires its
	 * `wp_abilities_api_init`/`wp_abilities_api_categories_init` bootstrap
	 * exactly once per process, on first touch — registers Block MCP's
	 * abilities instead of finding the toggle off and no-oping. This file is
	 * the only place in the suite that touches the live Abilities API, so
	 * setting the option here (before any test method can trigger that
	 * first touch) is sufficient regardless of method execution order.
	 */
	public function set_up(): void {
		parent::set_up();
		update_option( Block_Abilities::ENABLED_OPTION, '1' );
	}

	/**
	 * Abilities_Registry::load_manifest() must parse the checked-in
	 * tools.manifest.json and return the full, current 32-tool set, matching
	 * the npm MCP server's tool list one-for-one (this includes the four
	 * templates tools — manifest registration is data-driven and doesn't
	 * depend on Tool_Executor actually knowing how to run a tool; see
	 * TemplateAbilitiesTest for coverage that the templates abilities also
	 * execute correctly and honor their write gate).
	 *
	 * The manifest (generated by scripts/export-abilities-manifest.mjs) is
	 * the only thing register_abilities() reads: if it fails to parse — or
	 * loads a stale set because a tool was added/removed in src/tools/*.ts
	 * without regenerating it — register_abilities() treats a null or empty
	 * result as "nothing to register" and silently no-ops rather than
	 * erroring, so an agent on the WordPress Abilities transport would see
	 * fewer tools than the npm server advertises with no signal why.
	 */
	public function test_manifest_lists_all_block_mcp_tools() {
		$registry = new Abilities_Registry(
			new Tool_Executor( $this->controller, new Yoast_Bridge() ),
			$this->controller
		);

		$reflection = new \ReflectionClass( $registry );
		$method     = $reflection->getMethod( 'load_manifest' );
		$method->setAccessible( true );
		$manifest = $method->invoke( $registry );

		$this->assertIsArray( $manifest );
		$this->assertCount( 32, $manifest['tools'] );
		$names = wp_list_pluck( $manifest['tools'], 'name' );
		$this->assertContains( 'get_page_blocks', $names );
		$this->assertContains( 'edit_block_tree', $names );
		$this->assertContains( 'site_editor_context', $names );
		$this->assertContains( 'list_templates', $names );
		$this->assertContains( 'get_template', $names );
		$this->assertContains( 'update_template', $names );
		$this->assertContains( 'reset_template', $names );
	}

	/**
	 * Tool_Executor::execute('resolve_url', …) must delegate to
	 * REST_Controller::resolve_url() and return the resolved post_id.
	 *
	 * resolve_url is the ability layer's URL-to-post_id lookup;
	 * execute_get_page_blocks() falls back to it whenever a caller supplies a
	 * url instead of a post_id, so a broken dispatch here would silently
	 * break every ability chained off a URL rather than an id, not just this
	 * one. Pins that the executor's routing and param-passing reach the real
	 * REST handler and surface its resolved post_id, not a stub, an empty
	 * result, or a WP_Error.
	 */
	public function test_tool_executor_resolve_url_returns_post_id() {
		$post_id = self::factory()->post->create(
			array(
				'post_title'  => 'Abilities Resolve Target',
				'post_status' => 'publish',
			)
		);

		$user_id = self::factory()->user->create( array( 'role' => 'editor' ) );
		wp_set_current_user( $user_id );

		$executor = new Tool_Executor( $this->controller, new Yoast_Bridge() );
		$result   = $executor->execute(
			'resolve_url',
			array( 'url' => get_permalink( $post_id ) )
		);

		$this->assertIsArray( $result );
		$this->assertSame( $post_id, (int) $result['post_id'] );
	}

	/**
	 * Tool_Executor::execute('list_patterns') must report the true total across
	 * pages and offer a next_offset when more patterns remain.
	 *
	 * The executor fetched only offset+limit patterns and then used that window's
	 * size as `total`, so on a full first page `next_offset` was always null and
	 * every pattern past the first page was invisible to an agent.
	 */
	public function test_execute_list_patterns_reports_true_total_across_pages() {
		for ( $i = 0; $i < 5; $i++ ) {
			register_block_pattern(
				'gktest/pat' . $i,
				array(
					'title'   => 'Test Pattern ' . $i,
					'content' => '<!-- wp:paragraph --><p>p' . $i . '</p><!-- /wp:paragraph -->',
				)
			);
		}

		$user_id = self::factory()->user->create( array( 'role' => 'editor' ) );
		wp_set_current_user( $user_id );

		$executor = new Tool_Executor( $this->controller, new Yoast_Bridge() );
		$result   = $executor->execute( 'list_patterns', array( 'limit' => 2, 'offset' => 0 ) );

		$this->assertIsArray( $result );
		$this->assertCount( 2, $result['patterns'], 'the first page returns limit rows' );
		$this->assertGreaterThanOrEqual( 5, (int) $result['total'], 'total must reflect all patterns, not the fetched window' );
		$this->assertSame( 2, (int) $result['next_offset'], 'a full first page with more patterns must offer a next_offset' );
	}

	/**
	 * Ability ids use the gk-block-mcp namespace and dashed slugs.
	 *
	 * Count excludes the three yoast_* tools: get_ability_ids() reflects what
	 * actually registers, which is conditional on Yoast being active, unlike
	 * the manifest itself (still 32 — test_manifest_lists_all_block_mcp_tools).
	 * This test is untagged, so it only ever runs in the default (non-Yoast)
	 * suite.
	 */
	public function test_ability_ids_use_expected_namespace() {
		$registry = new Abilities_Registry(
			new Tool_Executor( $this->controller, new Yoast_Bridge() ),
			$this->controller
		);

		$ids = $registry->get_ability_ids();
		$this->assertCount( 29, $ids );
		$this->assertContains( 'gk-block-mcp/get-page-blocks', $ids );
		$this->assertContains( 'gk-block-mcp/edit-block-tree', $ids );
		$this->assertContains( 'gk-block-mcp/site-editor-context', $ids );
		$this->assertContains( 'gk-block-mcp/list-templates', $ids );
		$this->assertContains( 'gk-block-mcp/get-template', $ids );
		$this->assertContains( 'gk-block-mcp/update-template', $ids );
		$this->assertContains( 'gk-block-mcp/reset-template', $ids );
		$this->assertNotContains( 'gk-block-mcp/yoast-get-seo', $ids );
	}

	/**
	 * Yoast abilities must not be registered when Yoast SEO isn't active —
	 * Tool_Executor's yoast_* handlers hard-fail with `yoast_unavailable`
	 * otherwise, so registering them would advertise abilities that always
	 * error. Runs under the default (non-Yoast) suite only; the positive
	 * case is covered by test_yoast_abilities_registered_when_yoast_active()
	 * under tests/phpunit/yoast.xml.
	 *
	 * Reads the plugin bootstrap's live registration (already run on the
	 * init hooks) rather than re-registering — see
	 * test_registered_abilities_are_mcp_public() for why. wp_get_ability() on
	 * an id that was never registered triggers WP core's own
	 * _doing_it_wrong(), which this test must expect rather than let the
	 * framework flag as an unhandled notice.
	 */
	public function test_yoast_abilities_not_registered_when_yoast_inactive() {
		$this->assertFalse( Yoast_Bridge::is_yoast_active(), 'sanity: this test must run where Yoast is not loaded' );

		$registry = new Abilities_Registry(
			new Tool_Executor( $this->controller, new Yoast_Bridge() ),
			$this->controller
		);

		$ids = $registry->get_ability_ids();
		$this->assertNotContains( 'gk-block-mcp/yoast-get-seo', $ids );
		$this->assertNotContains( 'gk-block-mcp/yoast-update-seo', $ids );
		$this->assertNotContains( 'gk-block-mcp/yoast-bulk-update-seo', $ids );

		$this->setExpectedIncorrectUsage( 'WP_Abilities_Registry::get_registered' );
		$this->assertNull( wp_get_ability( 'gk-block-mcp/yoast-get-seo' ) );
		$this->assertNull( wp_get_ability( 'gk-block-mcp/yoast-update-seo' ) );
		$this->assertNull( wp_get_ability( 'gk-block-mcp/yoast-bulk-update-seo' ) );
	}

	/**
	 * Mirror of test_yoast_abilities_not_registered_when_yoast_inactive() for
	 * the positive case: when Yoast SEO is active, the three yoast_* tools
	 * ARE registered as abilities (and the manifest's full 32 count is
	 * reachable). Tagged `@group yoast` so it only runs under
	 * tests/phpunit/yoast.xml, the one config that loads Yoast SEO
	 * (GK_LOAD_YOAST=1) — the default suite excludes the yoast group, so
	 * this never runs where Yoast is absent.
	 *
	 * @group yoast
	 */
	public function test_yoast_abilities_registered_when_yoast_active() {
		$this->assertTrue( Yoast_Bridge::is_yoast_active(), 'sanity: this test must run where Yoast is loaded' );

		$registry = new Abilities_Registry(
			new Tool_Executor( $this->controller, new Yoast_Bridge() ),
			$this->controller
		);

		$ids = $registry->get_ability_ids();
		$this->assertCount( 32, $ids );
		$this->assertContains( 'gk-block-mcp/yoast-get-seo', $ids );
		$this->assertContains( 'gk-block-mcp/yoast-update-seo', $ids );
		$this->assertContains( 'gk-block-mcp/yoast-bulk-update-seo', $ids );

		$this->assertNotNull( wp_get_ability( 'gk-block-mcp/yoast-get-seo' ) );
		$this->assertNotNull( wp_get_ability( 'gk-block-mcp/yoast-update-seo' ) );
		$this->assertNotNull( wp_get_ability( 'gk-block-mcp/yoast-bulk-update-seo' ) );
	}

	/**
	 * Executing yoast-get-seo on a real, editable post must return its Yoast
	 * SEO fields, not a not_found error.
	 *
	 * Regression coverage for Tool_Executor::execute_yoast_get_seo(): the REST
	 * route is `/yoast/(?P<post_id>\d+)` and both Yoast_Bridge::get_seo() and
	 * ::check_permissions() read `get_param('post_id')`, but the executor set
	 * the target via `$request->set_param('id', $post_id)` and never passed
	 * `post_id` through call_controller()'s $params. `get_param('post_id')`
	 * then resolved to null -> `(int) null` -> 0 -> `get_post(0)` fails, so
	 * every call to this ability 404'd with `not_found` regardless of the
	 * caller's actual permissions.
	 *
	 * @group yoast
	 */
	public function test_yoast_get_seo_ability_returns_fields() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = self::factory()->post->create( array( 'post_status' => 'publish' ) );

		$result = wp_get_ability( 'gk-block-mcp/yoast-get-seo' )->execute( array( 'post_id' => $post_id ) );

		$this->assertNotWPError( $result );
		$this->assertIsArray( $result );
		$this->assertSame( $post_id, (int) $result['post_id'] );
	}

	/**
	 * Executing yoast-update-seo must persist a writable field — round-tripped
	 * here via a follow-up yoast-get-seo read — rather than fail with
	 * not_found before any field is written.
	 *
	 * Same root cause as test_yoast_get_seo_ability_returns_fields(), for the
	 * write path: Tool_Executor::execute_yoast_update_seo() wrote the target
	 * as `id` (via set_param() and the $params array) instead of `post_id`,
	 * so Yoast_Bridge::update_seo() — which also reads `get_param('post_id')`
	 * — resolved the target post as 0 and every call 404'd with `not_found`.
	 *
	 * @group yoast
	 */
	public function test_yoast_update_seo_ability_round_trips_focus_keyword() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = self::factory()->post->create( array( 'post_status' => 'publish' ) );

		$result = wp_get_ability( 'gk-block-mcp/yoast-update-seo' )->execute(
			array(
				'post_id'       => $post_id,
				'focus_keyword' => 'block mcp abilities',
			)
		);
		$this->assertNotWPError( $result );

		$read = wp_get_ability( 'gk-block-mcp/yoast-get-seo' )->execute( array( 'post_id' => $post_id ) );
		$this->assertNotWPError( $read );
		$this->assertSame( 'block mcp abilities', $read['focus_keyword'] );
	}

	/**
	 * yoast-get-seo must deny an Author reading another author's Yoast SEO
	 * metadata, matching the per-post `edit_post` gate its REST twin
	 * (`Yoast_Bridge::check_permissions()`) already enforces — while still
	 * allowing the post's own author to read it.
	 *
	 * Regression coverage for scripts/export-abilities-manifest.mjs's
	 * permissionFor(): yoast_get_seo was mapped to the manifest permission
	 * 'read', which Abilities_Registry::check_tool_permission() resolves to
	 * REST_Controller::check_permissions() — a global `edit_posts` check with
	 * no awareness of the target post. An Author has `edit_posts` but not
	 * `edit_others_posts`, so they could read another author's SEO metadata
	 * through the ability even though the REST route itself would 403 the
	 * identical request. The fix maps yoast_get_seo to the 'edit_post'
	 * permission, which additionally checks
	 * `current_user_can('edit_post', post_id)`.
	 *
	 * @group yoast
	 */
	public function test_yoast_get_seo_ability_denies_reading_another_authors_post() {
		$owner_id = self::factory()->user->create( array( 'role' => 'author' ) );
		$post_id  = self::factory()->post->create(
			array(
				'post_status' => 'publish',
				'post_author' => $owner_id,
			)
		);

		$other_author = self::factory()->user->create( array( 'role' => 'author' ) );
		wp_set_current_user( $other_author );

		$this->setExpectedIncorrectUsage( 'WP_Ability::execute' );
		$denied = wp_get_ability( 'gk-block-mcp/yoast-get-seo' )->execute( array( 'post_id' => $post_id ) );
		$this->assertWPError( $denied, "an author without edit_others_posts must not read another author's SEO metadata" );
		$this->assertSame( 'ability_invalid_permissions', $denied->get_error_code() );

		wp_set_current_user( $owner_id );
		$allowed = wp_get_ability( 'gk-block-mcp/yoast-get-seo' )->execute( array( 'post_id' => $post_id ) );
		$this->assertNotWPError( $allowed, "the post's own author must still be able to read their own SEO metadata" );
	}

	/**
	 * Every registered ability carries meta.mcp.public = true and type = tool.
	 *
	 * This is what the MCP Adapter's discover-abilities meta-tool filters on;
	 * without it the abilities register in WordPress but are invisible over MCP.
	 * Pin it so the flag can never silently regress.
	 *
	 * Reads the plugin bootstrap's live registration (already run on the init
	 * hooks) instead of re-registering — WordPress 6.9 warns on duplicate
	 * ability registration, so calling wp_register_ability() again here would
	 * itself trigger a notice the test would have to suppress for no reason.
	 */
	public function test_registered_abilities_are_mcp_public() {
		if ( ! function_exists( 'wp_register_ability' ) ) {
			$this->markTestSkipped( 'Abilities API unavailable (requires WordPress 6.9+).' );
		}

		$registry = new Abilities_Registry(
			new Tool_Executor( $this->controller, new Yoast_Bridge() ),
			$this->controller
		);

		$ability = wp_get_ability( 'gk-block-mcp/get-page-blocks' );
		$this->assertNotNull( $ability, 'ability must be registered' );

		$meta = $ability->get_meta();
		$this->assertArrayHasKey( 'mcp', $meta, 'meta.mcp is required for MCP discovery' );
		$this->assertTrue( $meta['mcp']['public'], 'meta.mcp.public must be true' );

		foreach ( $registry->get_ability_ids() as $id ) {
			$a = wp_get_ability( $id );
			$this->assertNotNull( $a, $id . ' must be registered' );
			$m = $a->get_meta();
			$this->assertTrue(
				isset( $m['mcp']['public'] ) && true === $m['mcp']['public'],
				$id . ' must be mcp.public'
			);
		}
	}

	/**
	 * The site-editor-context ability returns the site's design tokens so an
	 * agent composes theme-aligned, valid block markup (preset slugs instead
	 * of raw hex/px) — the WordPress-recommended prevention move. Restored
	 * from develop's hand-written Block_Abilities into the manifest-driven
	 * registry; execution now lives in Tool_Executor::execute_site_editor_context().
	 */
	public function test_site_editor_context_ability_returns_presets() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/site-editor-context' )->execute();

		$this->assertNotWPError( $result );
		$this->assertIsArray( $result );
		$this->assertArrayHasKey( 'theme', $result );
		$this->assertArrayHasKey( 'presets', $result );
		$this->assertArrayHasKey( 'colors', $result['presets'] );
		$this->assertIsArray( $result['presets']['colors'] );
	}

	/**
	 * site-editor-context must carry annotations.readonly = true.
	 *
	 * The ability only reads the site's registered design tokens (see
	 * test_site_editor_context_ability_returns_presets()) and performs no
	 * mutation, so MCP clients that skip confirmation prompts on readonly
	 * tools must be able to trust the hint. The flag comes from the
	 * tools.manifest.json EXTRA_TOOLS entry (scripts/export-abilities-manifest.mjs)
	 * added when this ability was restored into the manifest-driven registry;
	 * pin it so a manifest edit can't silently drop the annotation and force
	 * needless confirmation friction on a purely informational tool.
	 */
	public function test_site_editor_context_is_readonly() {
		$meta = wp_get_ability( 'gk-block-mcp/site-editor-context' )->get_meta();
		$this->assertTrue( $meta['annotations']['readonly'] );
	}

	/**
	 * Registration is opt-in: with the option unset (a fresh install's
	 * default), Block_Abilities::is_enabled() reads the '0' fallback and
	 * reports disabled. set_up() above forces the option on for every other
	 * test in this file, so this test explicitly overrides it back rather
	 * than relying on an untouched option.
	 */
	public function test_abilities_disabled_by_default() {
		delete_option( Block_Abilities::ENABLED_OPTION );
		$this->assertFalse( Block_Abilities::is_enabled() );
	}

	/**
	 * Block_Abilities::is_enabled() must return true once the stored option
	 * is explicitly '1' — the Settings toggle's "on" write.
	 *
	 * Sibling of test_abilities_disabled_by_default() (unset -> off) and
	 * test_setting_disables_abilities() (explicit '0' -> off); together the
	 * three pin every state the option can be in. A regression here means
	 * turning the Settings toggle on has no effect: abilities would stay
	 * unregistered even though the operator opted in.
	 */
	public function test_setting_enables_abilities() {
		update_option( Block_Abilities::ENABLED_OPTION, '1' );
		$this->assertTrue( Block_Abilities::is_enabled() );
	}

	/**
	 * Block_Abilities::is_enabled() must return false when the stored option
	 * is explicitly '0', not only when it is unset.
	 *
	 * Boolean options in this plugin are stored as the strings '0'/'1' (a
	 * hidden '0' input pairs with the '1' checkbox, since update_option()
	 * can't reliably persist a literal false against a missing option — see
	 * the repo AGENTS.md code-style notes). A regression that checked only
	 * `! empty()` or raw truthiness of the option, instead of the exact
	 * string, would leave abilities registered after an operator explicitly
	 * flips the Settings toggle off.
	 */
	public function test_setting_disables_abilities() {
		update_option( Block_Abilities::ENABLED_OPTION, '0' );
		$this->assertFalse( Block_Abilities::is_enabled() );
	}

	/**
	 * The gk/block-mcp/abilities/enabled filter overrides a truthy option,
	 * for programmatic control (matching the allow-trash pattern used
	 * elsewhere in the plugin).
	 */
	public function test_filter_can_disable_abilities() {
		update_option( Block_Abilities::ENABLED_OPTION, '1' );
		add_filter( 'gk/block-mcp/abilities/enabled', '__return_false' );
		$enabled = Block_Abilities::is_enabled();
		remove_filter( 'gk/block-mcp/abilities/enabled', '__return_false' );
		$this->assertFalse( $enabled );
	}

	/**
	 * End-to-end: with the option unset, the plugin bootstrap's
	 * get_abilities_registry() (gk-block-mcp.php) returns null and never
	 * builds an Abilities_Registry — the gate holds at the bootstrap seam
	 * actually wired to WordPress, not only inside Block_Abilities::is_enabled().
	 *
	 * get_abilities_registry() memoizes a successful build in a process-wide
	 * static, and WP_Abilities_Registry::get_instance() (WordPress core)
	 * fires its own init hooks exactly once per process, on the first
	 * wp_get_ability()/wp_has_ability() touch. Every other test in this file
	 * enables abilities in set_up() and is the sole intended toucher of the
	 * live Abilities API for the whole suite (see set_up() docblock), so
	 * running this assertion in-process would either observe an
	 * already-warmed registry (false pass) or permanently consume the
	 * one-shot WordPress init hook while abilities are disabled, breaking
	 * every other test in this file for the rest of the process.
	 * @runInSeparateProcess guarantees a pristine process where this is the
	 * first and only touch of both statics.
	 *
	 * @runInSeparateProcess
	 * @preserveGlobalState disabled
	 */
	public function test_bootstrap_does_not_build_abilities_registry_when_disabled_by_default() {
		delete_option( Block_Abilities::ENABLED_OPTION );
		$this->assertNull( get_abilities_registry() );
	}

	/**
	 * The permission callback gates writes on edit_post for the target post:
	 * a user without any capability gets the Abilities API's
	 * ability_invalid_permissions, never the effect. WP_Ability::execute()
	 * logs a _doing_it_wrong() when the permission callback itself returns a
	 * WP_Error (rather than false), which this test must expect.
	 */
	public function test_update_block_ability_denies_without_capability() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = $this->make_block_post( array( $this->paragraph( '<p>Old</p>' ) ) );

		wp_set_current_user( 0 );
		$this->setExpectedIncorrectUsage( 'WP_Ability::execute' );
		$result = wp_get_ability( 'gk-block-mcp/update-block' )->execute(
			array(
				'post_id'    => $post_id,
				'flat_index' => 0,
				'innerHTML'  => '<p>New</p>',
			)
		);

		$this->assertWPError( $result );
		$this->assertSame( 'ability_invalid_permissions', $result->get_error_code() );
		$this->assertStringContainsString( '<p>Old</p>', $this->block_tree( $post_id )[0]['innerHTML'], 'content must be untouched' );
	}

	/**
	 * The edit_post permission branch has two halves: a global edit_posts
	 * check, then (when the input carries post_id) a per-post
	 * current_user_can('edit_post', post_id) check. The sibling test above
	 * (test_update_block_ability_denies_without_capability) only exercises the
	 * first half — a fully logged-out user fails before the per-post check
	 * ever runs. This test pins the second half: an Author has edit_posts
	 * globally (passes the first check) but lacks edit_others_posts, so
	 * targeting another author's post must still be denied.
	 *
	 * Pins current, already-correct behavior in
	 * Abilities_Registry::check_tool_permission()'s default/edit_post branch —
	 * the same per-post half whose absence of coverage on the read branch let
	 * Fix 3's yoast_get_seo over-permission ship green (see
	 * test_yoast_get_seo_ability_denies_reading_another_authors_post).
	 */
	public function test_update_block_ability_denies_without_per_post_capability() {
		$owner_id = self::factory()->user->create( array( 'role' => 'author' ) );
		$post_id  = $this->make_block_post(
			array( $this->paragraph( '<p>Old</p>' ) ),
			array( 'post_author' => $owner_id )
		);

		wp_set_current_user( self::factory()->user->create( array( 'role' => 'author' ) ) );
		$this->setExpectedIncorrectUsage( 'WP_Ability::execute' );
		$result = wp_get_ability( 'gk-block-mcp/update-block' )->execute(
			array(
				'post_id'    => $post_id,
				'flat_index' => 0,
				'innerHTML'  => '<p>New</p>',
			)
		);

		$this->assertWPError( $result );
		$this->assertSame( 'ability_invalid_permissions', $result->get_error_code() );
		$this->assertStringContainsString( '<p>Old</p>', $this->block_tree( $post_id )[0]['innerHTML'], 'content must be untouched' );
	}

	/**
	 * The read permission branch (Abilities_Registry::check_tool_permission()'s
	 * 'read' case) denies a subscriber, who lacks the global edit_posts
	 * capability the branch checks. Pins the branch itself — distinct from
	 * test_yoast_get_seo_ability_denies_reading_another_authors_post, which
	 * pins the per-post edit_post branch a read-shaped ability was moved to.
	 */
	public function test_list_block_types_ability_denies_subscriber() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'subscriber' ) ) );

		$this->setExpectedIncorrectUsage( 'WP_Ability::execute' );
		$result = wp_get_ability( 'gk-block-mcp/list-block-types' )->execute( array() );

		$this->assertWPError( $result );
		$this->assertSame( 'ability_invalid_permissions', $result->get_error_code() );
	}

	/**
	 * The manage_options permission branch
	 * (Abilities_Registry::check_tool_permission()'s 'manage_options' case)
	 * denies a non-admin (an Editor, who has edit_posts and edit_others_posts
	 * but not manage_options) rather than falling through to a lesser check.
	 */
	public function test_scan_storage_modes_ability_denies_non_admin() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );

		$this->setExpectedIncorrectUsage( 'WP_Ability::execute' );
		$result = wp_get_ability( 'gk-block-mcp/scan-storage-modes' )->execute( array() );

		$this->assertWPError( $result );
		$this->assertSame( 'ability_invalid_permissions', $result->get_error_code() );
	}

	/**
	 * Read/discovery abilities are annotated readonly; the mutating
	 * update-block ability is not. The annotation is the hint MCP clients
	 * use to label a tool.
	 */
	public function test_read_abilities_are_annotated_readonly() {
		$get    = wp_get_ability( 'gk-block-mcp/get-page-blocks' )->get_meta();
		$list   = wp_get_ability( 'gk-block-mcp/list-block-types' )->get_meta();
		$update = wp_get_ability( 'gk-block-mcp/update-block' )->get_meta();
		$templates = wp_get_ability( 'gk-block-mcp/list-templates' )->get_meta();
		$template  = wp_get_ability( 'gk-block-mcp/get-template' )->get_meta();

		$this->assertTrue( $get['annotations']['readonly'] );
		$this->assertTrue( $list['annotations']['readonly'] );
		$this->assertFalse( $update['annotations']['readonly'] );
		$this->assertTrue( $templates['annotations']['readonly'] );
		$this->assertTrue( $template['annotations']['readonly'] );
	}

	/**
	 * Every write ability declares an explicit destructive annotation
	 * matching its behavior rather than the core null default (which MCP
	 * treats as destructive). update-block and update-blocks overwrite
	 * existing block content — both TRUE, the manifest's current
	 * destructiveHint semantics; insert-blocks and create-post only add
	 * content — FALSE; delete-block removes blocks — TRUE. update-template
	 * replaces a whole template and reset-template deletes an override —
	 * both TRUE, matching src/tools/templates.ts's WRITE_ANNOT.
	 */
	public function test_write_abilities_declare_destructive_annotation() {
		$update  = wp_get_ability( 'gk-block-mcp/update-block' )->get_meta()['annotations'];
		$updates = wp_get_ability( 'gk-block-mcp/update-blocks' )->get_meta()['annotations'];
		$insert  = wp_get_ability( 'gk-block-mcp/insert-blocks' )->get_meta()['annotations'];
		$create  = wp_get_ability( 'gk-block-mcp/create-post' )->get_meta()['annotations'];
		$delete  = wp_get_ability( 'gk-block-mcp/delete-block' )->get_meta()['annotations'];
		$update_template = wp_get_ability( 'gk-block-mcp/update-template' )->get_meta()['annotations'];
		$reset_template  = wp_get_ability( 'gk-block-mcp/reset-template' )->get_meta()['annotations'];

		$this->assertTrue( $update['destructive'], 'update-block overwrites existing block content' );
		$this->assertTrue( $updates['destructive'], 'update-blocks overwrites existing block content' );
		$this->assertFalse( $insert['destructive'], 'insert-blocks only adds blocks' );
		$this->assertFalse( $create['destructive'], 'create-post only adds a post' );
		$this->assertTrue( $delete['destructive'], 'delete-block removes blocks' );
		$this->assertTrue( $update_template['destructive'], 'update-template replaces a whole template' );
		$this->assertTrue( $reset_template['destructive'], 'reset-template deletes an override' );
	}

	/**
	 * A non-numeric post_id is rejected by input-schema validation
	 * (rest_validate_value_from_schema against the manifest's declared
	 * "type": "number") before the execute callback ever runs — a
	 * WordPress Abilities API structural guarantee, not bespoke plugin code.
	 */
	public function test_update_block_rejects_non_numeric_post_id() {
		$result = wp_get_ability( 'gk-block-mcp/update-block' )->execute(
			array(
				'post_id'    => 'not-a-number',
				'flat_index' => 0,
				'innerHTML'  => '<p>x</p>',
			)
		);
		$this->assertWPError( $result );
		$this->assertSame( 'ability_invalid_input', $result->get_error_code() );
	}

	/**
	 * insert-blocks position -1 is the documented "append" sentinel
	 * (after_top_level: -1, matching the REST `after` and npm MCP server
	 * contracts) and must keep working through the ability layer. Pins
	 * commit 2e8428d's -1 contract; a pure pin of current behavior (proven
	 * green-on-current, no revert needed — the sibling rejection test below
	 * is the one that proves the actual guard with red/green teeth).
	 */
	public function test_insert_blocks_ability_position_negative_one_still_appends() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = $this->make_block_post( array( $this->paragraph( '<p>A</p>' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/insert-blocks' )->execute(
			array(
				'post_id'         => $post_id,
				'after_top_level' => -1,
				'blocks'          => array(
					array(
						'name'      => 'core/paragraph',
						'innerHTML' => '<p>NEW</p>',
					),
				),
			)
		);

		$this->assertNotWPError( $result );
		$blocks = $this->block_tree( $post_id );
		$this->assertCount( 2, $blocks );
		$this->assertStringContainsString( '<p>NEW</p>', $blocks[1]['innerHTML'] );
	}

	/**
	 * A position more negative than the documented -1 append sentinel has no
	 * defined meaning. Block_Writer::insert_blocks() rejects it with a 400
	 * invalid_position WP_Error (commit 2e8428d) rather than silently
	 * clamping to a prepend; the ability layer must surface that error
	 * unchanged, not swallow or remap it. This pins the fix itself, so it
	 * carries red/green teeth (proven by temporarily reverting the guard).
	 */
	public function test_insert_blocks_ability_rejects_position_more_negative_than_append_sentinel() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = $this->make_block_post( array( $this->paragraph( '<p>A</p>' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/insert-blocks' )->execute(
			array(
				'post_id'         => $post_id,
				'after_top_level' => -2,
				'blocks'          => array(
					array(
						'name'      => 'core/paragraph',
						'innerHTML' => '<p>NEW</p>',
					),
				),
			)
		);

		$content = (string) get_post_field( 'post_content', $post_id );
		$this->assertWPError( $result, 'a position more negative than -1 must error, not silently prepend' );
		$this->assertSame( 'invalid_position', $result->get_error_code() );
		$this->assertStringNotContainsString( '<p>NEW</p>', $content, 'no block may be inserted' );
		$this->assertStringContainsString( '<p>A</p>', $content );
	}

	/**
	 * Executing update-block delegates through Tool_Executor to the same
	 * REST_Controller::update_block() path the REST endpoint uses, and the
	 * change persists to post_content.
	 *
	 * Regression coverage for the Tool_Executor::call_controller() bug fixed
	 * in commit c7690c9: route params (here, post_id and flat_index) were
	 * written via WP_REST_Request::set_param(), which for a fresh,
	 * undispatched request lands in the POST parameter bucket; the very next
	 * step, set_body_params(), unconditionally replaced that whole bucket and
	 * silently dropped them. update-block always pairs a target post with a
	 * JSON body, so every call resolved the post as 0 and failed permission
	 * with a generic "You do not have permission to edit this post," even for
	 * a user who could otherwise edit it. Route params now go into the URL
	 * parameter bucket via set_url_params(), which set_body_params() never
	 * touches.
	 */
	public function test_update_block_ability_persists_change() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = $this->make_block_post( array( $this->paragraph( '<p>Old</p>' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/update-block' )->execute(
			array(
				'post_id'    => $post_id,
				'flat_index' => 0,
				'innerHTML'  => '<p>New</p>',
			)
		);

		$this->assertNotWPError( $result );
		$this->assertStringContainsString( '<p>New</p>', $this->block_tree( $post_id )[0]['innerHTML'] );
	}

	/**
	 * Executing update-block addressed by `ref` (rather than `flat_index`)
	 * must persist the change, mirroring test_update_block_ability_persists_change().
	 *
	 * Regression coverage for the ref branch of Tool_Executor::execute_update_block():
	 * it wrote the target ref via WP_REST_Request::set_param('ref', ...) and never
	 * included `ref` in the $params array passed to call_controller(). set_param()
	 * on a fresh PATCH request lands in the POST parameter bucket, and
	 * call_controller()'s subsequent set_body_params($body) call (update-block always
	 * pairs a target with a JSON body) unconditionally replaces that whole bucket,
	 * dropping the ref. update_block_by_ref() then reads an empty ref and rejects
	 * with invalid_ref. This mirrors the id/flat_index bucket-collision bug fixed in
	 * commit c7690c9, which missed this ref-addressed branch. The fix routes `ref`
	 * through the $params (URL) argument, which set_body_params() never touches.
	 */
	public function test_update_block_ability_by_ref_persists_change() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = $this->make_block_post( array( $this->paragraph_with_ref( '<p>Old</p>', 'blk_ref_test1' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/update-block' )->execute(
			array(
				'post_id'   => $post_id,
				'ref'       => 'blk_ref_test1',
				'innerHTML' => '<p>New</p>',
			)
		);

		$this->assertNotWPError( $result );
		$this->assertStringContainsString( '<p>New</p>', $this->block_tree( $post_id )[0]['innerHTML'] );
	}

	/**
	 * Executing create-post delegates through Tool_Executor to Post_Manager,
	 * emitting canonical block-comment markup rather than a corrupted
	 * classic-editor blob.
	 */
	public function test_create_post_ability_creates_post() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/create-post' )->execute(
			array(
				'title'  => 'Via Ability',
				'blocks' => array(
					array(
						'name'      => 'core/paragraph',
						'innerHTML' => '<p>Hi</p>',
					),
				),
			)
		);

		$this->assertNotWPError( $result );
		$this->assertIsArray( $result );
		$this->assertArrayHasKey( 'id', $result );
		$this->assertStringContainsString( '<!-- wp:paragraph', (string) get_post_field( 'post_content', $result['id'] ) );
	}

	/**
	 * Executing insert-blocks delegates through Tool_Executor to
	 * Block_CRUD::insert_blocks(); the new block is appended and persists.
	 *
	 * Regression coverage for the same Tool_Executor::call_controller() bug
	 * as test_update_block_ability_persists_change() (commit c7690c9):
	 * insert-blocks pairs a target post_id (a route param) with a JSON body,
	 * so it hit the same set_param()/set_body_params() bucket collision that
	 * dropped post_id and resolved the target post as 0, failing permission
	 * for a user who could otherwise edit the post.
	 */
	public function test_insert_blocks_ability_appends() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = $this->make_block_post( array( $this->paragraph( '<p>First</p>' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/insert-blocks' )->execute(
			array(
				'post_id' => $post_id,
				'blocks'  => array(
					array(
						'name'      => 'core/paragraph',
						'innerHTML' => '<p>Second</p>',
					),
				),
			)
		);

		$this->assertNotWPError( $result );
		$blocks = $this->block_tree( $post_id );
		$this->assertCount( 2, $blocks );
		$this->assertStringContainsString( '<p>Second</p>', $blocks[1]['innerHTML'] );
	}

	/**
	 * Executing get-page-blocks returns the structured block tree from the
	 * real reader, in the same {summary, blocks} shape REST_Controller::
	 * get_post_blocks() returns to the REST endpoint.
	 */
	public function test_get_page_blocks_ability_returns_tree() {
		wp_set_current_user( self::factory()->user->create( array( 'role' => 'editor' ) ) );
		$post_id = $this->make_block_post( array( $this->paragraph( '<p>Hello</p>' ) ) );

		$result = wp_get_ability( 'gk-block-mcp/get-page-blocks' )->execute( array( 'post_id' => $post_id ) );

		$this->assertNotWPError( $result );
		$this->assertIsArray( $result );
		$this->assertArrayHasKey( 'blocks', $result );
		$this->assertNotEmpty( $result['blocks'] );
	}

	/**
	 * Build a flat core/paragraph block in WP-internal shape, for seeding
	 * make_block_post() fixtures (distinct from the {name, innerHTML} MCP
	 * shape ability payloads use for insert-blocks/create-post `blocks`).
	 *
	 * @param string $html Paragraph innerHTML.
	 * @return array
	 */
	private function paragraph( string $html ): array {
		return array(
			'blockName'    => 'core/paragraph',
			'attrs'        => array(),
			'innerHTML'    => $html,
			'innerContent' => array( $html ),
			'innerBlocks'  => array(),
		);
	}

	/**
	 * Same as paragraph(), with a hand-assigned metadata.gk_ref so a test can
	 * address the block by ref instead of relying on the lazily-assigned one.
	 *
	 * @param string $html Paragraph innerHTML.
	 * @param string $ref  Stable ref to assign.
	 * @return array
	 */
	private function paragraph_with_ref( string $html, string $ref ): array {
		return array(
			'blockName'    => 'core/paragraph',
			'attrs'        => array( 'metadata' => array( 'gk_ref' => $ref ) ),
			'innerHTML'    => $html,
			'innerContent' => array( $html ),
			'innerBlocks'  => array(),
		);
	}
}
